name: CI-CD Tests

on:
  push:
    branches:
    - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: instal dependancies
        run: pip install -r requirements.txt

      - name: run test cases
        run: pytest --cov=maths --cov-report=term --cov-report=html --cov-fail-under=80

      - name: Downloading cov report file
        uses: actions/upload-artifact@v4
        with:
          name: html-code-cov-report
          path: htmlcov/

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: print Message
        run: echo "deploy job started..."